# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='side',
            field=models.TextField(null=True),
        ),
    ]
