# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tw', '0003_imagegallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagegallery',
        ),
    ]
