# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
