# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0003_delete_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagegallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('image4', models.FileField(blank=True, null=True, upload_to='')),
                ('image5', models.FileField(blank=True, null=True, upload_to='')),
                ('image6', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
